### ISSUE TITLE
introduction to nsq

### ISSUE THREAD

**Issue by metrue** [metrue/board#4]
1. https://news.ycombinator.com/item?id=14455825

**Comment by metrue** [comment]
nsq 第一次在 HN 上发布的时间是 Jan 26, 2015，https://news.ycombinator.com/item?id=8947354 ，受到了大量的关注，经过一段时间的成长 nsq 二次在 HN 的发帖是在 May 31, 2017, https://news.ycombinator.com/item?id=14451148 同样是受到大量关注.

而现在 nsq 已经在很多大小公司中都得到了广泛的应用，曾经 Segment 应该是 nsq 使用最大最深的应用[https://news.ycombinator.com/item?id=14455825] ，虽然他们之后不断的向 Kafka 迁移. 具体的原因是可以参考这个里，有 Engineer@Segment 做了很详细的回答，关于为什么选择 Kafka，而不选择比如 AWS Kinesis, RabittMQ, 和其他。
简单来说就是有三个方面的考虑:
* 费用
* 数据丢失
* scale 的难易程度

**Comment by metrue** [comment]
## 简单入门

nsq 的安装很简单. 它的文档也很清楚 [https://nsq.io/deployment/installing.html]
* Mac 下可以直接 brew install nsq
* 也可以直接用 go get github.com/nsqio/nsq/...
* 也可以直接下载其二进制文件
* 当然也可以直接从源码编译

安装了 nsq 之后，我们需要启动 nsq 的相关服务来进行使用: nsqd, nsqlookup, nsqadmin.

**Comment by metrue** [comment]
当然我们也可以直接用 docker-compose 来启动整个服务.
```
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
```
